[package]
authors = ["Raum Dellamorte <elementalsin@gmail.com>"]
name = "raum-en"
version = "0.1.0"
[dependencies]
cgmath = "0.16.1"
env_logger = "0.5"
gl = "0.10.0"
glutin = "0.17.0"
image = "0.18"
log = "0.4"
noise = "0.5.1"
nom = "^4.0"
num = "*"
piston = "0.37.0"
time = "^0.1.37"
